version: "3"
services:
  nat:
    build: .
    container_name: nat
    restart: always
    network_mode: host
    command:
      - /app/nat
      - '-b'
      - '-laddr'
      - '127.0.0.1:5212'
      - fqdn
      - 'drive.iakl.top'
      - stun
      - '114.115.218.1:2023'